# builder/section_u5.py

def get_unit5():
    return '''# Unit V: Converters and Semiconductor Memories

---

### Master Subject Map: Unit V Position
```
[ UNIT IV: SEQUENTIAL CIRCUITS & STATE MACHINES ]
                                  │
                                  ▼
┌──────────────────────────────────────────────────────────────────────────────────┐
│ YOU ARE HERE ──► UNIT V: CONVERTERS & SEMICONDUCTOR MEMORIES                     │
│ • D/A Converters: Weighted-Resistor (Summing Op-Amp), R-2R Ladder, DAC0808 IC    │
│ • A/D Converters: Counter-Type, SAR (Binary Search), Dual-Slope, ADC0801/0808    │
│ • Semiconductor Memories: Organization (2^k × m), Read/Write Cycles, Expansion  │
│ • Memory Classification: Volatile vs Non-Volatile, SRAM (6T) vs DRAM (1T-1C)    │
│ • Programmable Logic Devices (PLDs): Architectures of PROM, PAL, and PLA         │
└─────────────────────────────────┬────────────────────────────────────────────────┘
                                  ▼
[ REAL-WORLD DIGITAL SYSTEMS: Complete Microcomputer & Signal Processing Architectures ]
```
*In 3 lines:* Units I through IV built the internal brain of a digital computer. Unit V completes the subject by connecting that digital brain to the physical universe. We master **DACs and ADCs** to translate between continuous real-world voltages and digital bits, explore mass **Semiconductor Memories (RAM & ROM)**, and examine user-customizable silicon chips (**PLDs: PROM, PAL, PLA**).

---

### Prerequisites for this Unit
Before studying Unit V, ensure you recall these concepts:
1. **Ohm's Law & Circuit References (Prereqs 1 & 2):** Current $I = V/R$, Ground ($0\\text{ V}$), and Op-Amp Virtual Ground ($V_- \\approx 0\\text{ V}$).
2. **Binary Weights & Positional Values (Unit I, Section 1.1):** Binary digits carry weights $2^{-1} = 0.5$, $2^{-2} = 0.25$, $2^{-3} = 0.125$, etc.
3. **Binary Counters & Shift Registers (Unit IV, Sections 4.8–4.10):** Stepping sequentially through states on clock edges.
4. **Decoders (Unit III, Section 3.8):** A $k$-to-$2^k$ decoder activates exactly one row wire for memory word addressing.

---

## PART 1: Digital-to-Analog Converters (DAC)

### 5.1 The Need for DAC and Key Specifications
*Source: Kumar (Ch. 17, pp. 941–946, Figures 17.1 & 17.2); Floyd (Ch. 9, pp. 487–492)*  
**[Pacing: Intuitive Foundations — Bridging Bits to Continuous Reality]**

#### Need (Problem-First)
Microprocessors calculate with discrete numbers (e.g., `11010010`). But physical actuators do not understand numbers. An audio speaker requires a continuously undulating analog voltage to move its cone; an electric vehicle motor requires a continuous voltage to set its speed; an MRI scanner requires continuous magnetic coils. How can a computer convert a digital binary word into a proportional continuous physical voltage? That bridge is the **Digital-to-Analog Converter (DAC)**.

#### Key DAC Performance Specifications Defined Inline:
1. **Resolution:** The smallest analog voltage increment that the DAC can produce. It corresponds to the voltage generated by a change of the **Least Significant Bit (LSB)** (*Kumar*, p. 944):
   $$\\text{Step Size } (\\Delta V) = \\frac{V_{FS}}{2^n - 1}$$
   Where $V_{FS}$ is the Full-Scale output voltage and $n$ is the number of digital bits.
   *Concrete Round-Number Example:* An 8-bit DAC ($n=8$) has $2^8 - 1 = 255$ intervals. If $V_{FS} = 5.10\\text{ V}$, the resolution is:
   $$\\Delta V = \\frac{5.10\\text{ V}}{255} = 0.02\\text{ V} = 20\\text{ mV per step}$$
2. **Full-Scale Output ($V_{FS}$):** The maximum analog output voltage produced when all input bits are $1$ (`1111...1`).
3. **Linearity:** How strictly the analog output follows a perfect straight line across all digital input codes.
4. **Accuracy:** The deviation between the actual measured analog output and the ideal theoretical output.
5. **Settling Time ($t_s$):** The time required for the analog output to settle within $\\pm \\frac{1}{2}\\text{ LSB}$ of its final value after an input code transition.

---

### 5.2 The Binary Weighted-Resistor DAC
*Source: Kumar (Ch. 17, pp. 951–953, Figure 17.10)*  
**[Pacing: Derivation Step-by-Step — Trace the Summing Node]**

#### How It Works (The Physical Mechanism)
The circuit connects an Operational Amplifier (Op-Amp) configured as an **inverting summing amplifier**, with binary input switches driving resistors whose values are scaled inversely to their binary weights ($R, 2R, 4R, 8R$):

<figure>
  <img src="images/fig_u5_weighted_resistor_dac.png" alt="Figure 17.10 Weighted-resistor type DAC" width="550"/>
  <figcaption><strong>Figure 17.10:</strong> Binary Weighted-Resistor type Digital-to-Analog Converter using an operational amplifier summing network. Sourced from <em>A. Anand Kumar, Fundamentals of Digital Circuits (4th Ed.)</em>, p. 951 (printed p. 919).</figcaption>
</figure>

##### Characteristic 13 Walkthrough: Hardware Reality Check
1. The non-inverting terminal ($+$) of the op-amp is connected to Ground ($0\\text{ V}$).
2. Due to negative feedback through $R_f$, the inverting terminal ($-$) is held at **Virtual Ground ($0.00\\text{ V}$)** (*Kumar*, p. 951).
3. Digital bits ($D_3, D_2, D_1, D_0$) control electronic switches. If bit $D_i = 1$, the resistor is connected to reference voltage $-V_{ref}$; if $D_i = 0$, the resistor is connected to ground ($0\\text{ V}$).
4. The current flowing through each weighted resistor is determined strictly by Ohm's Law into virtual ground:
   - $I_3 = \\frac{V_{ref}}{R} D_3$ (MSB current)
   - $I_2 = \\frac{V_{ref}}{2R} D_2 = \\frac{1}{2} I_3$
   - $I_1 = \\frac{V_{ref}}{4R} D_1 = \\frac{1}{4} I_3$
   - $I_0 = \\frac{V_{ref}}{8R} D_0 = \\frac{1}{8} I_3$ (LSB current)
5. Because the op-amp input draws zero current, by Kirchhoff's Current Law, all individual branch currents sum into the feedback resistor $R_f$:
   $$I_{\\text{total}} = I_3 + I_2 + I_1 + I_0 = \\frac{V_{ref}}{R} \\left(D_3 + \\frac{1}{2}D_2 + \\frac{1}{4}D_1 + \\frac{1}{8}D_0\\right)$$
6. The output voltage is the drop across $R_f$:
   $$V_{out} = -I_{\\text{total}} \\cdot R_f = -V_{ref} \\frac{R_f}{R} \\left(D_3 2^{-0} + D_2 2^{-1} + D_1 2^{-2} + D_0 2^{-3}\\right)$$

##### The Fatal Engineering Flaw of Weighted Resistors: The Resistor Spread Problem
In a 4-bit DAC, resistors range from $R$ to $8R$ (a factor of 8). But in a modern **12-bit DAC**, the resistors must range from $R$ to $2^{11}R = 2048R$!
- If $R = 10\\text{ k}\\Omega$, the LSB resistor must be $20.48\\text{ M}\\Omega$!
- **Fabrication Disaster:** In integrated circuit silicon manufacturing, it is virtually impossible to fabricate resistors spanning four orders of magnitude ($10\\text{ k}\\Omega$ to $20\\text{ M}\\Omega$) that track each other accurately across temperature changes. A tiny $0.05\\%$ error in the MSB resistor completely swamps the entire LSB current!

---

### 5.3 The R-2R Ladder DAC: The Universal Solution
*Source: Kumar (Ch. 17, pp. 946–950, Figure 17.5); Floyd (Ch. 9, pp. 490–492)*  
**[Pacing: Conceptually Brilliant — Master Why Two Resistor Values Suffice]**

#### Need (Problem-First)
We need a digital-to-analog converter that works for any number of bits (8, 12, 16, or 24 bits) but uses **only TWO precision resistor values** that can be effortlessly matched on a silicon die. That circuit is the **R-2R Ladder**.

#### The R-2R Ladder Circuit Architecture (*Kumar*, p. 947, Figure 17.5)

<figure>
  <img src="images/fig_u5_r2r_ladder_dac.png" alt="Figure 17.5 R-2R ladder type DAC" width="550"/>
  <figcaption><strong>Figure 17.5:</strong> Schematic diagram of an R-2R ladder Digital-to-Analog Converter feeding an operational amplifier buffer. Sourced from <em>A. Anand Kumar, Fundamentals of Digital Circuits (4th Ed.)</em>, p. 947 (printed p. 915).</figcaption>
</figure>

##### Why It Works: The Continuous Binary Current Division
The R-2R ladder uses only two resistor values: $R$ (e.g., $10\\text{ k}\\Omega$) and $2R$ (e.g., $20\\text{ k}\\Omega$).  
- Look at the termination on the extreme left: a vertical $2R$ resistor is in parallel with another $2R$ resistor. Their equivalent parallel resistance is:
  $$2R \\parallel 2R = R$$
- This equivalent $R$ is in series with the horizontal resistor $R$, yielding $R + R = 2R$!
- At the next node, this $2R$ is in parallel with the vertical $2R$, yielding $R$ again!
- **The Binary Splitting Principle:** Looking into *any* node of the ladder toward the left, the equivalent resistance is **always exactly $R$**!
- Therefore, at every single node, incoming current splits **exactly in half ($50\\% / 50\\%$)**!
- The currents arriving at the summing bus are naturally, automatically weighted in exact powers of two:
  $$\\frac{I}{2}, \\quad \\frac{I}{4}, \\quad \\frac{I}{8}, \\quad \\frac{I}{16} \\dots$$
- **Output Equation:**
  $$V_{out} = V_{ref} \\left(\\frac{D_3}{2^1} + \\frac{D_2}{2^2} + \\frac{D_1}{2^3} + \\frac{D_0}{2^4}\\right)$$
- **Manufacturing Triumph:** Because only two resistor values are required, laser-trimmed thin-film silicon resistors maintain near-perfect tracking over temperature, making R-2R the foundation of commercial DACs.

##### Commercial DAC Example: DAC0808 / DAC0800 IC (*Kumar*, pp. 954–955)
An 8-bit monolithic multiplying DAC featuring an R-2R ladder, fast settling time ($150\\text{ ns}$), and full 8-bit accuracy ($\pm 0.19\\%$).

---

## PART 2: Analog-to-Digital Converters (ADC)

### 5.4 The Need for ADC and Key Parameters
*Source: Kumar (Ch. 17, pp. 957–968); Floyd (Ch. 9, pp. 492–502)*  
**[Pacing: Intuitive Foundations — Translating the Analog World into Bits]**

#### Need (Problem-First)
The real physical world is entirely analog. Sound waves entering a microphone, engine temperatures measured by a thermocouple, and blood pressure in a medical monitor are continuous, fluid voltages. A digital computer cannot directly process an infinite continuum of values. We must sample the continuous signal and quantize it into a sequence of binary words. That device is the **Analog-to-Digital Converter (ADC)**.

#### Key ADC Specifications Defined Inline:
1. **Resolution:** The number of bits in the output binary word (e.g., 8-bit, 12-bit, 16-bit). An $n$-bit ADC divides the analog voltage range into $2^n$ discrete quantization levels.
2. **Quantization Error ($Q_e$):** Because a continuous voltage is rounded to the nearest discrete digital level, an inherent rounding error exists in all ADCs (*Kumar*, p. 957):
   $$Q_e = \\pm \\frac{1}{2} \\text{ LSB}$$
   This error can never be eliminated by circuit tuning; it is reduced only by adding more bits.
3. **Conversion Time ($t_c$):** The total elapsed time from the command to start conversion (Start of Conversion, $SOC$) to the moment the valid digital word appears at the output pins (End of Conversion, $EOC$).

---

### 5.5 Counting (Ramp) ADC
*Source: Kumar (Ch. 17, pp. 958–960, Figure 17.15)*  
**[Pacing: Simple & Intuitive — The Staircase Comparator Method]**

#### How It Works (The Physical Mechanism)
The Counter-Type ADC uses a **closed-loop feedback system** consisting of an analog comparator, a binary counter, and an internal DAC (*Kumar*, p. 958, Figure 17.15):

<figure>
  <img src="images/fig_u5_counter_type_adc.png" alt="Figure 17.15 Logic diagram of counter-type ADC" width="550"/>
  <figcaption><strong>Figure 17.15:</strong> Logic schematic of a Counter-Type (Ramp) Analog-to-Digital Converter. Sourced from <em>A. Anand Kumar, Fundamentals of Digital Circuits (4th Ed.)</em>, p. 958 (printed p. 926).</figcaption>
</figure>

##### Characteristic 13 Walkthrough: Hardware Reality Check
1. A **Start pulse** resets the binary counter to `0000`. The DAC output voltage is $V_{DAC} = 0\\text{ V}$.
2. The analog input voltage $V_A$ is connected to the non-inverting ($+$) input of the comparator, and $V_{DAC}$ connects to the inverting ($-$) input.
3. Because $V_A > V_{DAC}$, the comparator outputs **HIGH ($1$)**, which enables an AND gate, allowing master clock pulses to enter the counter.
4. The counter counts upward ($0, 1, 2, 3 \\dots$), causing the internal DAC output $V_{DAC}$ to climb upward like a **staircase ramp**.
5. The instant $V_{DAC}$ climbs just a fraction of a millivolt above $V_A$ ($V_{DAC} \\ge V_A$), the comparator output **snaps LOW ($0\\text{ V}$)**!
6. The AND gate is instantly inhibited, freezing the clock. The counter stops counting.
7. The binary word frozen in the counter is the exact digital equivalent of the input voltage $V_A$!

##### Limitation: Variable and Slow Conversion Time
- If $V_A$ is small (e.g., $0.1\\text{ V}$), the counter stops in 5 clock cycles.
- If $V_A$ is full-scale, an 8-bit counter must count through all **$2^8 = 256$ clock cycles**!
- In an $n$-bit counter, the maximum conversion time is:
  $$t_{\\text{max}} = 2^n \\times T_{\\text{clock}}$$
  This massive variation in conversion time makes the counting ADC too slow for audio or video.

---

### 5.6 Successive Approximation ADC (SAR ADC)
*Source: Kumar (Ch. 17, pp. 965–967, Figure 17.24); Floyd (Ch. 9, pp. 494–498)*  
**[Pacing: Conceptually Heavy — The Binary Search Algorithm in Hardware]**

#### Need (Problem-First)
We need an ADC that is fast, highly accurate, and has a **fixed, predictable conversion time** that does not depend on whether the input voltage is high or low.

#### The Binary Search Algorithm in Hardware (*Kumar*, p. 965, Figure 17.24)
Instead of counting up slowly by 1s (like a linear search), the SAR ADC uses an intelligent **binary search algorithm** (the same strategy you use when guessing a secret number between 1 and 100 by guessing 50 first):

<figure>
  <img src="images/fig_u5_sar_adc.png" alt="Figure 17.24 The successive-approximation type ADC" width="450"/>
  <figcaption><strong>Figure 17.24:</strong> Block diagram of a Successive-Approximation Register (SAR) Analog-to-Digital Converter. Sourced from <em>A. Anand Kumar, Fundamentals of Digital Circuits (4th Ed.)</em>, p. 965 (printed p. 933).</figcaption>
</figure>

##### Characteristic 13 Walkthrough: Step-by-Step Conversion
Consider a 4-bit SAR ADC with full-scale $V_{FS} = 16\\text{ V}$ (each step is $1\\text{ V}$).  
Suppose the incoming analog voltage is **$V_A = 11.4\\text{ V}$**.
- **Clock Cycle 1 (Test MSB, $D_3 = 8\\text{ V}$):**  
  SAR sets MSB to $1$: trial word = `1000` ($8\\text{ V}$).  
  Internal DAC produces $8\\text{ V}$.  
  Comparator tests: Is $V_A (11.4\\text{ V}) > 8\\text{ V}$? **YES!**  
  **Decision:** Keep $D_3 = 1$.
- **Clock Cycle 2 (Test Next Bit, $D_2 = 4\\text{ V}$):**  
  SAR sets $D_2$ to $1$: trial word = `1100` ($8 + 4 = 12\\text{ V}$).  
  Internal DAC produces $12\\text{ V}$.  
  Comparator tests: Is $V_A (11.4\\text{ V}) > 12\\text{ V}$? **NO!** (It's too high!)  
  **Decision:** Reset $D_2 = 0$.
- **Clock Cycle 3 (Test Next Bit, $D_1 = 2\\text{ V}$):**  
  SAR sets $D_1$ to $1$: trial word = `1010` ($8 + 0 + 2 = 10\\text{ V}$).  
  Internal DAC produces $10\\text{ V}$.  
  Comparator tests: Is $V_A (11.4\\text{ V}) > 10\\text{ V}$? **YES!**  
  **Decision:** Keep $D_1 = 1$.
- **Clock Cycle 4 (Test LSB, $D_0 = 1\\text{ V}$):**  
  SAR sets $D_0$ to $1$: trial word = `1011` ($8 + 0 + 2 + 1 = 11\\text{ V}$).  
  Internal DAC produces $11\\text{ V}$.  
  Comparator tests: Is $V_A (11.4\\text{ V}) > 11\\text{ V}$? **YES!**  
  **Decision:** Keep $D_0 = 1$.
- **End of Conversion (EOC):** The SAR asserts the $EOC$ pin. Final digital word = **`1011` ($11_{10}$)**!
- **Fixed Conversion Time:** Notice that for an $n$-bit SAR ADC, conversion **always takes exactly $n$ clock cycles**!
  $$t_{\\text{conversion}} = n \\times T_{\\text{clock}}$$
  An 8-bit SAR ADC finishes in just **8 clock cycles**, over **30 times faster** than a counting ADC!

##### Commercial ADC IC: ADC0801 / ADC0808 (*Kumar*, p. 967, Figure 17.25)
A classic 8-bit successive approximation ADC with on-chip clock generator, active-low chip select ($\overline{CS}$), write/start ($\overline{WR}$), and end-of-conversion interrupt ($\overline{INTR}$).

---

### 5.7 Dual-Slope Integrating ADC
*Source: Kumar (Ch. 17, pp. 964–965, Figure 17.23); Floyd (Ch. 9, pp. 498–500)*  
**[Pacing: Mathematical Masterpiece — The Heart of Digital Multimeters]**

#### Need (Problem-First)
In industrial and medical measurement instruments (like digital multimeters), high speed is not required, but **extreme precision and total immunity to $50\\text{ Hz} / 60\\text{ Hz}$ AC power line noise** are mandatory. SAR ADCs suffer from component drift in their DAC resistors. We need an ADC whose mathematical accuracy is **completely independent of component tolerances (independent of $R$ and $C$)**! That converter is the **Dual-Slope Integrating ADC**.

#### The Dual-Slope Circuit & Waveform (*Kumar*, p. 964, Figure 17.23)

<figure>
  <img src="images/fig_u5_dual_slope_adc.png" alt="Figure 17.23 The dual-slope ADC" width="550"/>
  <figcaption><strong>Figure 17.23:</strong> Functional block diagram of the Dual-Slope Integrating ADC. Sourced from <em>A. Anand Kumar, Fundamentals of Digital Circuits (4th Ed.)</em>, p. 964 (printed p. 932).</figcaption>
</figure>

##### The Two Mathematical Integration Phases:
1. **Phase 1: Run-Up (Fixed Time Interval $T_1$):**  
   The electronic switch connects the op-amp integrator to the unknown analog input voltage $V_{in}$ (assumed negative, or inverted). The integrator charges its capacitor $C$ through resistor $R$ for a **fixed time period $T_1$** (governed by the time it takes an $n$-bit counter to count to full scale, $2^n$ clock cycles):
   $$V_{\\text{peak}} = -\\frac{1}{RC} \\int_0^{T_1} V_{in}\\, dt = \\frac{V_{in} \\cdot T_1}{RC}$$
   Notice that the peak voltage reached is directly proportional to $V_{in}$.
2. **Phase 2: Run-Down (Variable Time Interval $T_2$):**  
   At the exact moment $T_1$ expires, the control logic flips the switch to a fixed, highly stable reference voltage $-V_{ref}$ of opposite polarity. The counter resets to zero and starts counting again. The integrator discharges back toward zero:
   $$0 = V_{\\text{peak}} - \\frac{V_{ref} \\cdot T_2}{RC}$$
   Equating the two expressions:
   $$\\frac{V_{in} \\cdot T_1}{RC} = \\frac{V_{ref} \\cdot T_2}{RC}$$
   **Divide both sides by $RC$:**
   $$V_{in} \\cdot T_1 = V_{ref} \\cdot T_2 \\quad \\iff \\quad \\mathbf{V_{in} = V_{ref} \\left(\\frac{T_2}{T_1}\\right)}$$

##### The Mathematical Miracle of Dual-Slope:
*Look at that equation!* **The resistance $R$, capacitance $C$, and master clock frequency $f$ have completely cancelled out of the equation!**  
Even if your resistor shifts by $10\\%$ due to heat or your capacitor ages, the measured voltage $V_{in}$ remains **100% mathematically exact**!
- By setting $T_1$ to an exact multiple of the AC power line period ($20\\text{ ms}$ for $50\\text{ Hz}$ or $16.67\\text{ ms}$ for $60\\text{ Hz}$), AC line hum integrates to exactly zero, providing infinite noise rejection.

---

## PART 3: Semiconductor Memories and Programmable Logic Devices (PLDs)

### 5.8 Memory Organization, Word Capacity, and Read/Write Operations
*Source: Kumar (Ch. 18, pp. 974–978, Figures 18.1 & 18.2); Mano (Ch. 7, pp. 410–418)*  
**[Pacing: Architectural System View — High Relevance to Computer Hardware]**

#### Memory Terminology Defined Inline:
- **Memory Cell:** The elementary 1-bit bistable storage unit.
- **Word:** A group of binary bits that are stored or retrieved together as a unit (e.g., 8-bit byte, 16-bit word, 32-bit word, 64-bit word).
- **Address:** The unique binary number designating the specific physical physical location of a word inside the memory array.
- **Capacity:** The total storage capability of the memory, designated as:
  $$\\text{Capacity} = 2^k \\times m$$
  Where $k$ is the number of **Address lines** (giving $2^k$ addressable words) and $m$ is the number of **Data lines** (bits per word) (*Kumar*, p. 975).
  *Example:* A memory chip with 10 address lines and 8 data lines has:
  $$\\text{Capacity} = 2^{10} \\times 8 = 1024 \\times 8 = 1\\text{ Kilobyte (1 KB)}$$

<figure>
  <img src="images/fig_u5_memory_organization.png" alt="Figure 18.1 Diagram of 32x4 memory and cell arrangement" width="550"/>
  <figcaption><strong>Figure 18.1:</strong> Block diagram of a 32 × 4 semiconductor memory array showing internal address decoding and cell matrix. Sourced from <em>A. Anand Kumar, Fundamentals of Digital Circuits (4th Ed.)</em>, p. 976 (printed p. 944).</figcaption>
</figure>

##### The Memory Read and Write Sequences (*Kumar*, p. 977):
- **Memory Write Cycle:**
  1. Apply the binary address to the address bus pins ($A_0$ to $A_{k-1}$).
  2. Place the data bits to be stored onto the data input bus ($D_0$ to $D_{m-1}$).
  3. Assert the active-low Chip Select ($\overline{CS}$) pin to enable the chip.
  4. Pulse the Write Enable ($\overline{WE}$) line LOW for a specified minimum write pulse width ($t_w$). The internal gates latch the data into the addressed cells.
- **Memory Read Cycle:**
  1. Apply the desired binary address to the address bus pins.
  2. Assert Chip Select ($\overline{CS}$) and Output Enable ($\overline{OE}$).
  3. Hold Write Enable ($\overline{WE}$) HIGH (Read mode).
  4. After an **Access Time ($t_{acc}$)**, the data stored in the addressed cells appears on the output pins.

---

### 5.9 Expanding Memory Size: Word Length and Word Capacity
*Source: Kumar (Ch. 18, pp. 984–989, Figures 18.7 & 18.9); Floyd (Ch. 9, pp. 505–510)*  
**[Pacing: Systematic Circuit Synthesis — Learn How Chips are Combined]**

#### Need (Problem-First)
In an embedded system, your processor requires a memory space of $1\\text{K} \\times 8$ (1024 bytes), but the only chips available in your inventory are $1\\text{K} \\times 4$ (each storing 4-bit nibbles). Or your system needs $2\\text{K} \\times 8$, but you only have $1\\text{K} \\times 8$ chips. How do you wire multiple small chips together to expand the total memory space?

---

#### 1. Expanding Word Length (Increasing Data Width) (*Kumar*, p. 985)
- **Goal:** Combine two $16 \\times 4$ memory chips to create a single $16 \\times 8$ memory module.
- **The Wiring Rule:**
  - Both chips must share the **exact same address bus lines** ($A_0, A_1, A_2, A_3$) in parallel so that identical memory locations are accessed simultaneously!
  - Both chips share the **exact same control lines** ($\overline{CS}, \overline{WE}$).
  - Chip 1 provides the lower 4 data bits ($D_0, D_1, D_2, D_3$).
  - Chip 2 provides the upper 4 data bits ($D_4, D_5, D_6, D_7$).

<figure>
  <img src="images/fig_u5_memory_word_length_expansion.png" alt="Figure 18.7 Combining two 16x4 RAMs for a 16x8 module" width="600"/>
  <figcaption><strong>Figure 18.7:</strong> Combining two 16 × 4 RAM chips to expand word length, creating a unified 16 × 8 memory module. Sourced from <em>A. Anand Kumar, Fundamentals of Digital Circuits (4th Ed.)</em>, p. 985 (printed p. 953).</figcaption>
</figure>

---

#### 2. Expanding Word Capacity (Increasing Total Addresses) (*Kumar*, p. 988)
- **Goal:** Combine two $16 \\times 4$ memory chips to create a single $32 \\times 4$ memory module.
- **The Wiring Rule:**
  - The module needs $32 = 2^5$ words $\\implies$ **5 address lines** ($A_4, A_3, A_2, A_1, A_0$).
  - The lower 4 address lines ($A_0, A_1, A_2, A_3$) are connected to both chips in parallel.
  - The data lines ($D_0, D_1, D_2, D_3$) of both chips are tied together in parallel to form a common data bus.
  - The highest address bit (**$A_4$**) is used to select which chip is active!
    - When $A_4 = 0$: Chip 1 is enabled via $\overline{CS}_1$ (addresses $0$ to $15$).
    - When $A_4 = 1$: Chip 2 is enabled via $\overline{CS}_2$ through an inverter (addresses $16$ to $31$).

<figure>
  <img src="images/fig_u5_memory_word_capacity_expansion.png" alt="Figure 18.9 Combining two 16x4 chips for 32x4 memory" width="550"/>
  <figcaption><strong>Figure 18.9:</strong> Combining two 16 × 4 RAM chips using an MSB address inverter to expand word capacity to 32 × 4. Sourced from <em>A. Anand Kumar, Fundamentals of Digital Circuits (4th Ed.)</em>, p. 988 (printed p. 956).</figcaption>
</figure>

---

### 5.10 Classification and Characteristics of Memories: SRAM vs. DRAM, ROM Families
*Source: Kumar (Ch. 18, pp. 978–984, Figure 18.5); Floyd (Ch. 9, pp. 510–525)*  
**[Pacing: Core Memory Technologies — Understand the Silicon Cells]**

#### The Master Memory Hierarchy:
- **Volatile Memory:** Loses its stored data the instant electric power is disconnected. (RAM).
- **Non-Volatile Memory:** Retains its stored binary data permanently, even with zero power applied. (ROM, Flash).

---

#### 1. Static RAM (SRAM) vs. Dynamic RAM (DRAM)

| Parameter | Static RAM (SRAM) | Dynamic RAM (DRAM) |
|---|---|---|
| **Storage Element** | Cross-coupled flip-flop (4 to 6 transistors) | Single MOSFET transistor + tiny capacitor ($1\\text{T}-1\\text{C}$) |
| **Silicon Cell Area** | Large (takes 4x more area per bit) | Microscopic (ultra-dense) |
| **Refresh Requirement** | **None** (stores data indefinitely while powered) | **Mandatory periodic refresh** (every few ms) |
| **Operating Speed** | Extremely fast ($1\\text{ to }5\\text{ ns}$) | Slower ($10\\text{ to }50\\text{ ns}$) |
| **Power Consumption** | Higher when switching; zero refresh overhead | Lower per bit; requires refresh controller power |
| **Application** | CPU L1/L2/L3 Caches | Main System Memory (Computer RAM sticks) |

<figure>
  <img src="images/fig_u5_sram_dram_cells.png" alt="Figure 18.5 Bipolar, NMOS, and CMOS RAM cells" width="450"/>
  <figcaption><strong>Figure 18.5:</strong> Circuit diagrams of Static RAM storage cells (bipolar, NMOS, and CMOS). Sourced from <em>A. Anand Kumar, Fundamentals of Digital Circuits (4th Ed.)</em>, p. 982 (printed p. 950).</figcaption>
</figure>

##### Why DRAM Needs Refreshing:
In DRAM, a bit `1` is stored as a tiny packet of electrostatic charge on an integrated capacitor ($\approx 30\\text{ femtofarads}$). Due to microscopic reverse-bias junction leakage, this charge bleeds away into the silicon substrate within tens of milliseconds! If left alone, a stored `1` will bleed down into a `0`. Therefore, a dedicated **DRAM Controller** must continuously read every row and restore the full charge thousands of times per second (the **Refresh Cycle**).

---

#### 2. The Read-Only Memory (ROM) Hierarchy
- **Mask ROM:** Data is permanently programmed into the silicon metallization layer during factory fabrication with chemical masks. Cheap in million-unit quantities, but cannot be modified.
- **PROM (Programmable ROM):** Manufactured with microscopic fusible links (nichrome or polysilicon). The user programs data in a PROM programmer by pulsing high current to physically **blow open selected fuses** ("burning" the ROM). It can be programmed only once!
- **EPROM (Erasable PROM):** Uses floating-gate MOS transistors. It can be erased by exposing the quartz window on the chip package to intense ultraviolet (UV) light for 20 minutes, which discharges the floating gates.
- **EEPROM (Electrically Erasable PROM):** Can be erased and rewritten electrically byte-by-byte in circuit, without UV light.
- **Flash Memory:** A high-density evolution of EEPROM that erases and writes data in whole blocks (pages), powering USB thumb drives and modern Solid-State Drives (SSDs).

---

### 5.11 Programmable Logic Devices (PLDs): PROM, PAL, and PLA
*Source: Kumar (Ch. 8, pp. 491–508, Figures 8.7, 8.8, 8.15); Mano (Ch. 7, pp. 430–445)*  
**[Pacing: Conceptually Heavy — The Three Architectures of Reconfigurable Silicon]**

#### Need (Problem-First)
In the 1970s, a complex digital product (like an arcade game or cash register) required hundreds of discrete 7400-series TTL chips wired together on massive printed circuit boards. Every design change required redesigning and etching a new circuit board. Engineers wanted a single standardized blank chip that could be configured on a programmer to implement *any arbitrary collection of logic functions*. These chips are **Programmable Logic Devices (PLDs)**.

#### The Three Core Architectures Compared (*Kumar*, p. 499, Figure 8.7)
Every two-level Boolean function can be expressed in Sum-of-Products (SOP) form:
$$F = \\sum(\\text{Product terms}) = \\text{OR of ANDs}$$
Therefore, a PLD consists of an array of **AND gates** (generating product terms) followed by an array of **OR gates** (summing the product terms).  
The difference between the three PLD types lies strictly in **which array is fixed and which array is programmable**:

<figure>
  <img src="images/fig_u5_pld_configurations.png" alt="Figure 8.7 Basic configuration of three PLDs" width="550"/>
  <figcaption><strong>Figure 8.7:</strong> Architectural comparison of the three fundamental Programmable Logic Devices: PROM, PAL, and PLA. Sourced from <em>A. Anand Kumar, Fundamentals of Digital Circuits (4th Ed.)</em>, p. 499 (printed p. 467).</figcaption>
</figure>

| PLD Type | AND Array | OR Array | Flexibility | Ease of Programming |
|---|---|---|---|---|
| **PROM** | **Fixed** (Full Decoder) | **Programmable** | Low | Very Easy |
| **PAL** | **Programmable** | **Fixed** | Moderate | High (Industry Favorite) |
| **PLA** | **Programmable** | **Programmable** | **Maximum** | More Complex |

---

#### 1. Programmable Array Logic (PAL) (*Kumar*, p. 500, Figure 8.8)
Invented by Monolithic Memories Inc. (MMI).  
- **Architecture:** The AND array is fully programmable (inputs and complements can be fused to any AND gate). The OR array is **hardwired and fixed** (each OR gate receives product terms from a fixed group of AND gates, e.g., 3 or 4 AND gates per OR gate):

<figure>
  <img src="images/fig_u5_pal_structure.png" alt="Figure 8.8 Basic structure of a PAL circuit" width="550"/>
  <figcaption><strong>Figure 8.8:</strong> Basic structure of a Programmable Array Logic (PAL) circuit showing unprogrammed fusible links (a) and programmed implementation of <em>F = A B' C' + A' B C</em> (b). Sourced from <em>A. Anand Kumar, Fundamentals of Digital Circuits (4th Ed.)</em>, p. 500 (printed p. 468).</figcaption>
</figure>

- **Advantage:** Eliminating the programmable OR array drastically reduces parasitic propagation delay, making PALs exceptionally fast and simple to program.

---

#### 2. Programmable Logic Array (PLA) (*Kumar*, p. 508, Figure 8.15)
- **Architecture:** **Both the AND array and the OR array are fully programmable**:

<figure>
  <img src="images/fig_u5_pla_structure.png" alt="Figure 8.15 Structure of an unprogrammed PLA circuit" width="450"/>
  <figcaption><strong>Figure 8.15:</strong> Internal matrix layout of an unprogrammed Programmable Logic Array (PLA) circuit showing programmable AND crosspoints and programmable OR crosspoints. Sourced from <em>A. Anand Kumar, Fundamentals of Digital Circuits (4th Ed.)</em>, p. 508 (printed p. 476).</figcaption>
</figure>

- **Why PLA is Superior for Complex Shared Systems:**  
  Because the OR array is programmable, multiple outputs can **share the exact same product term** from the AND array! If two functions both require the term $ABC$, a PLA generates $ABC$ once in the AND array and routes it to both OR gates, saving silicon area.

---

### Unit V Understanding Checkpoints & Misconception Audit

#### 1. Does This Make Sense? Self-Check
- **Question 1:** Why is an R-2R ladder preferred over a binary weighted-resistor network for high-resolution DACs?
  - **Answer:** Because an R-2R ladder requires only two precision resistor values ($R$ and $2R$), avoiding the unmanageable resistor spread (over $2000:1$ in 12-bit DACs) of weighted-resistor networks.
- **Question 2:** Why is the conversion accuracy of a Dual-Slope ADC completely independent of its resistor $R$ and capacitor $C$ values?
  - **Answer:** Because both the charging run-up phase ($T_1$) and discharging run-down phase ($T_2$) occur through the exact same $RC$ network, causing $R$ and $C$ to mathematically cancel out completely from the final voltage transfer equation.
- **Question 3:** What is the architectural difference between a PAL and a PLA?
  - **Answer:** A PAL has a programmable AND array with a fixed OR array. A PLA has both a programmable AND array and a programmable OR array.

#### 2. Conceptual Misconceptions Corrected
- **Misconception:** *"Dynamic RAM (DRAM) is faster than Static RAM (SRAM) because it is called 'dynamic'."*  
  **Correction:** The exact opposite is true! SRAM is significantly faster ($1\text{ to }5\text{ ns}$) because it uses active flip-flop latches. DRAM is slower ($10\text{ to }50\text{ ns}$) because charging and reading tiny capacitors takes time, and periodic refresh cycles block memory access.
- **Misconception:** *"A 16-bit ADC has zero error because 16 bits is very high precision."*  
  **Correction:** Every ADC has an unavoidable fundamental **Quantization Error of $\pm \frac{1}{2}\text{ LSB}$** caused by rounding continuous voltages to discrete binary levels.

---
'''

if __name__ == '__main__':
    print(get_unit5()[:300])
